version: 2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

jobs:
  test_validation:
    machine:
      enabled: true
      python:
        version: pypy-2.2.1

    steps:
      - checkout
      - run:
          name: install cloudify
          command: pip install -U cloudify==4.5
      - run:
          name: install test requirements
          command: pip install nose testtools https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/9e78969f30dcaa9efce9b8fd7b078357f3d8adc8.zip
      - run:
          name: download manager docker image
          command: wget http://repository.cloudifysource.org/cloudify/4.5.0/ga-release/cloudify-docker-manager-4.5ga.tar
      - run:
          name: load docker image
          command: docker load -i cloudify-docker-manager-4.5ga.tar
      - run:
          name: retain space by dumping the tar
          command: rm cloudify-docker-manager-4.5ga.tar
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host docker-cfy-manager:latest
      - run:
          name: init CLI profile
          command: |
            counter=0
            until [ $counter -ge 10 ]
            do
                cfy profiles use localhost -u admin -p admin -t default_tenant && break
                counter=$[$counter+1]
                sleep 2
            done
      - run: cfy plugins bundle-upload > /dev/null 2>&1
      - run: cfy blueprints upload azure.yaml -b azure > /dev/null 2>&1
      - run: cfy blueprints upload aws.yaml -b aws > /dev/null 2>&1
      - run: cfy blueprints upload openstack.yaml -b openstack > /dev/null 2>&1
      - run: cfy blueprints upload gcp.yaml -b gcp > /dev/null 2>&1
      - run: cfy blueprints upload vsphere.yaml -b vsphere > /dev/null 2>&1
      - run: cfy blueprints upload baremetal.yaml -b baremetal > /dev/null 2>&1
      - run: cfy blueprints upload hostpool.yaml -b hostpool > /dev/null 2>&1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_validation
